=== MaximePoujade/portfolio-Web-Semantique/languages/lang.dtd
<!ELEMENT root (fr,en,ja)>
        <!ELEMENT fr (commonData,mainPage,youtuberPresentation)>
        <!ELEMENT en (commonData,mainPage,youtuberPresentation)>
        <!ELEMENT ja (commonData,mainPage,youtuberPresentation)>
        <!ELEMENT commonData (resume,youtuberPage,templateLink)>
        <!ELEMENT mainPage (title,firstName,lastName,company,companyName,school,schoolName,aboutPosition,aboutDescription,experienceTitle,experienceName,experienceAddr,experienceDuration,experienceJobName,experienceDesc,educationTitle,education1SchoolName,education1Addr,education1Duration,education1Name,education1Desc,education2SchoolName,education2Addr,education2Duration,education2Name,education2Desc,education3SchoolName,education3Addr,education3Duration,education3Name,projectTitle,project1Name,project1Language,project1Desc,project2Name,project2Language,project2Desc,project3Name,project3Language,project3Desc,interestsTitle,interestsDesc)>
        <!ELEMENT youtuberPresentation (title,name,youtube,presentation,wikipedia,description,video)>
        <!ELEMENT title (#PCDATA)>
        <!ELEMENT firstName (#PCDATA)>
        <!ELEMENT lastName (#PCDATA)>
        <!ELEMENT company (#PCDATA)>
        <!ELEMENT companyName (#PCDATA)>
        <!ELEMENT school (#PCDATA)>
        <!ELEMENT schoolName (#PCDATA)>
        <!ELEMENT aboutPosition (#PCDATA)>
        <!ELEMENT aboutDescription (#PCDATA)>
        <!ELEMENT experienceTitle (#PCDATA)>
        <!ELEMENT experienceName (#PCDATA)>
        <!ELEMENT experienceAddr (#PCDATA)>
        <!ELEMENT experienceDuration (#PCDATA)>
        <!ELEMENT experienceJobName (#PCDATA)>
        <!ELEMENT experienceDesc (#PCDATA)>
        <!ELEMENT educationTitle (#PCDATA)>
        <!ELEMENT education1SchoolName (#PCDATA)>
        <!ELEMENT education1Addr (#PCDATA)>
        <!ELEMENT education1Duration (#PCDATA)>
        <!ELEMENT education1Name (#PCDATA)>
        <!ELEMENT education1Desc (#PCDATA)>
        <!ELEMENT education2SchoolName (#PCDATA)>
        <!ELEMENT education2Addr (#PCDATA)>
        <!ELEMENT education2Duration (#PCDATA)>
        <!ELEMENT education2Name (#PCDATA)>
        <!ELEMENT education2Desc (#PCDATA)>
        <!ELEMENT education3SchoolName (#PCDATA)>
        <!ELEMENT education3Addr (#PCDATA)>
        <!ELEMENT education3Duration (#PCDATA)>
        <!ELEMENT education3Name (#PCDATA)>
        <!ELEMENT projectTitle (#PCDATA)>
        <!ELEMENT project1Name (#PCDATA)>
        <!ELEMENT project1Language (#PCDATA)>
        <!ELEMENT project1Desc (#PCDATA)>
        <!ELEMENT project2Name (#PCDATA)>
        <!ELEMENT project2Language (#PCDATA)>
        <!ELEMENT project2Desc (#PCDATA)>
        <!ELEMENT project3Name (#PCDATA)>
        <!ELEMENT project3Language (#PCDATA)>
        <!ELEMENT project3Desc (#PCDATA)>
        <!ELEMENT interestsTitle (#PCDATA)>
        <!ELEMENT interestsDesc (#PCDATA)>
        <!ELEMENT resume (#PCDATA)>
        <!ELEMENT youtuberPage (#PCDATA)>
        <!ELEMENT templateLink (#PCDATA)>
        <!ELEMENT name (#PCDATA)>
        <!ELEMENT youtube (#PCDATA)>
        <!ELEMENT presentation (#PCDATA)>
        <!ELEMENT wikipedia (#PCDATA)>
        <!ELEMENT description (#PCDATA)>
        <!ELEMENT video (#PCDATA)>

=== MaximePoujade/portfolio-Web-Semantique/languages/lang.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE root SYSTEM "lang.dtd">
<root>
    <fr>
        <commonData>
            <resume>CV</resume>
            <youtuberPage>Présentation d'un youtuber</youtuberPage>
            <templateLink>Lien vers le template utilisé</templateLink>
        </commonData>
        <mainPage>
            <title>Mon Portfolio</title>
            <firstName>Maxime</firstName>
            <lastName>Poujade</lastName>
            <company>Entreprise :</company>
            <companyName>Dassault Systèmes</companyName>
            <school>École :</school>
            <schoolName>Sup-Galilée</schoolName>
            <aboutPosition>Apprenti en cursus ingénieur en informatique</aboutPosition>
            <aboutDescription>Je suis un apprenti ingénieur en informatique actuellement en alternance chez Dassault Systèmes, ma mission est d&#x27;améliorer l&#x27;outil de monitoring de l&#x27;équipe que j&#x27; ai rejoins.</aboutDescription>
            <experienceTitle>Expérience</experienceTitle>
            <experienceName>Dassault Systèmes</experienceName>
            <experienceAddr>Vélizy-Villacoublay - France</experienceAddr>
            <experienceDuration>Septembre 2022 - Aujourd&#x27;hui</experienceDuration>
            <experienceJobName>Développeur JAVA/WEB</experienceJobName>
            <experienceDesc>Travail sur un outil de monitoring interne</experienceDesc>
            <educationTitle>Formation</educationTitle>
            <education1SchoolName>Institut Galilée</education1SchoolName>
            <education1Addr>Villetaneuse - Seine-Saint-Denis</education1Addr>
            <education1Duration>Septembre 2022 - Aujourd&#x27;hui</education1Duration>
            <education1Name>Formation ingénieur en alternance</education1Name>
            <education1Desc>Cursus informatique</education1Desc>
            <education2SchoolName>Institut Galilée</education2SchoolName>
            <education2Addr>Villetaneuse - Seine-Saint-Denis</education2Addr>
            <education2Duration>Septembre 2021 - Juillet 2022</education2Duration>
            <education2Name>Formation ingénieur</education2Name>
            <education2Desc>Cursus informatique</education2Desc>
            <education3SchoolName>Institut Galilée</education3SchoolName>
            <education3Addr>Villetaneuse - Seine-Saint-Denis</education3Addr>
            <education3Duration>Septembre 2019 - Juillet 2021</education3Duration>
            <education3Name>Cursus Préparatoire Ingénieur Intégré</education3Name>
            <projectTitle>Projets</projectTitle>
            <project1Name>Morpion et MENACE</project1Name>
            <project1Language>C</project1Language>
            <project1Desc>Conception d&#x27;un jeu de tic-tac-toe et d&#x27;une intelligence artificielle de type MENACE jouant à ce jeu</project1Desc>
            <project2Name>TETRIS</project2Name>
            <project2Language>C</project2Language>
            <project2Desc>Conception d&#x27;un jeu de TETRIS à l&#x27;aide de la librairie SDL2</project2Desc>
            <project3Name>Concepteur et résolveur de labyrinthe</project3Name>
            <project3Language>JAVA</project3Language>
            <project3Desc>Conception d&#x27;un générateur/solveur de labyrinthe</project3Desc>
            <interestsTitle>Centre d&#x27;intérêts</interestsTitle>
            <interestsDesc>Badminton, Jeux Vidéos</interestsDesc>
        </mainPage>
        <youtuberPresentation>
            <title>Présentation d'un youtuber</title>
            <name>MrBeast</name>
            <youtube>youtube :</youtube>
            <presentation>Présentation</presentation>
            <wikipedia>texte provenant de wikipédia :</wikipedia>
            <description>Jimmy Donaldson a commencé sa carrière sur YouTube en 2012 à 13 ans, sous le pseudonyme « MrBeast6000 » ; ses premiers contenus allaient de Let's Plays à « des vidéos évaluant la richesse des autres YouTubeurs ». Cependant, ses vidéos sont restées dans l'obscurité relative — avec une moyenne d'environ mille vues chacune — jusqu'à la sortie de sa vidéo de 2017 « Je compte jusqu'à 100 000 » qui « a gagné des dizaines de milliers de vues en seulement quelques jours ». Le 8 février 2022, MrBeast atteint la barre des 90 millions d'abonnés sur sa chaîne YouTube. Le 28 juillet 2022, sa chaîne principale atteint les 100 millions d'abonnés et devient la cinquième chaine YouTube dépassant ce chiffre, et la deuxième chaine individuelle après PewDiePie. En novembre 2022, sa chaîne devient la plus suivie sur Youtube avec 112 millions de personnes suivies.

                Il a créé plusieurs chaînes en anglais en plus de sa chaîne principale, notamment une chaîne où il joue a des jeux vidéo qui se nomme MrBeast Gaming, une chaîne où il réagit à des vidéos intitulée Beast Reacts, une chaîne où il poste des vidéos bonus nommée MrBeast 2, une chaîne où il poste des vidéos de philanthropie nommée Beast Philanthropy et une chaîne où il poste des vidéos courtes de moins d'une minute intitulée Beast Shorts.

                Depuis le mois de juillet 2021 , il a créé des chaînes dans des langues étrangères à l'anglais et fait doubler ses vidéos en espagnol, en français, en portugais, en russe, en hindi et en arabe. </description>
            <video>Vidéo</video>
        </youtuberPresentation>
    </fr>
    <en>
        <commonData>
            <resume>Resume</resume>
            <youtuberPage>Presentation of a youtuber</youtuberPage>
            <templateLink>Link to the template used</templateLink>
        </commonData>
        <mainPage>
            <title>My Portfolio</title>
            <firstName>Maxime</firstName>
            <lastName>Poujade</lastName>
            <company>Company:</company>
            <companyName>3DS</companyName>
            <school>School:</school>
            <schoolName>Sup-Galilée</schoolName>
            <aboutPosition>Computer engineering apprentice</aboutPosition>
            <aboutDescription>I am an apprentice computer engineer currently on a work-study program at Dassault Systèmes, my main mission is to improve the internal monitoring tool of the team I joined.</aboutDescription>
            <experienceTitle>Experience</experienceTitle>
            <experienceName>3DS</experienceName>
            <experienceAddr>Vélizy-Villacoublay - France</experienceAddr>
            <experienceDuration>September 2022 - Today</experienceDuration>
            <experienceJobName>JAVA/WEB developer</experienceJobName>
            <experienceDesc>Work on an internal monitoring tool</experienceDesc>
            <educationTitle>Education</educationTitle>
            <education1SchoolName>Institut Galilée</education1SchoolName>
            <education1Addr>Villetaneuse - Seine-Saint-Denis</education1Addr>
            <education1Duration>September 2022 - Today</education1Duration>
            <education1Name>Apprenticeship Education Program</education1Name>
            <education1Desc>Major in computer science</education1Desc>
            <education2SchoolName>Institut Galilée</education2SchoolName>
            <education2Addr>Villetaneuse - Seine-Saint-Denis</education2Addr>
            <education2Duration>September 2021 - July 2022</education2Duration>
            <education2Name>Engineering program</education2Name>
            <education2Desc>Major in computer science</education2Desc>
            <education3SchoolName>Institut Galilée</education3SchoolName>
            <education3Addr>Villetaneuse - Seine-Saint-Denis</education3Addr>
            <education3Duration>September 2019 - July 2021</education3Duration>
            <education3Name>preparatory class</education3Name>
            <projectTitle>Projects</projectTitle>
            <project1Name>Morpion and MENACE</project1Name>
            <project1Language>C</project1Language>
            <project1Desc>Design of a tic-tac-toe game and a MENACE type artificial intelligence playing this game</project1Desc>
            <project2Name>TETRIS</project2Name>
            <project2Language>C</project2Language>
            <project2Desc>Design of a TETRIS game using the SDL2 library</project2Desc>
            <project3Name>Maze designer and solver</project3Name>
            <project3Language>JAVA</project3Language>
            <project3Desc>Design of a maze generator/solver</project3Desc>
            <interestsTitle>Interests</interestsTitle>
            <interestsDesc>Badminton, Video games</interestsDesc>
        </mainPage>
        <youtuberPresentation>
            <title>Introducing a youtuber</title>
            <name>MrBeast</name>
            <youtube>youtube:</youtube>
            <presentation>Presentation</presentation>
            <wikipedia>text from wikipedia:</wikipedia>
            <description>James Stephen "Jimmy" Donaldson (born May 7, 1998), better known as MrBeast, is an American YouTuber and philanthropist. He is credited with pioneering a genre of YouTube videos that centers on expensive stunts. His YouTube channel reached 130 million subscribers in January 2023, making it the fourth-most-subscribed on the platform.
